name: Build and Push Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Backend Image build & push
    - name: Build Backend Image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/journeo-backend:latest ./backend

    - name: Push Backend Image
      run: docker push ghcr.io/${{ github.repository_owner }}/journeo-backend:latest

    # Frontend Image build & push
    - name: Build Frontend Image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/journeo-frontend:latest ./frontend

    - name: Push Frontend Image
      run: docker push ghcr.io/${{ github.repository_owner }}/journeo-frontend:latest

    # DB-Image does not need to be pushed
